version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    ports:
      - "8070:80"
      - "9100:9000"
      - "9200:9003"
    networks:
      - phpexcel-network

networks:
  phpexcel-network:
    driver: bridge
